<!-- resources/views/vendor/openpolice/nodes/1712-report-inc-staff-tools-first-about-types.blade.php -->
<div class="mTn15 pB30">
    <p>
        <b>Police Complaint</b><br />
        Every submission describing a police incident goes 
        into the OpenPolice.org database. These should include 
        an incident time and place and at least one law enforcement 
        agency, officer, and misconduct allegation.
    </p>
    <p>
        <b>These are other common submissions types.</b>
    </p>
    <ul>
    <li><b>Not About Law Enforcement</b><br />
    We don't file these submissions with police investigative agencies. 
    Instead, we store them in a secondary anonymized dataset on OpenPolice.org. 
    Common examples include complaints about government service agencies or 
    complaints related to unidentified stalking or surveillance entities.
    </li>
    <li><b>Corrections Case</b><br />
    These are misconduct complaints against corrections officials. 
    Due to concerns about retaliation against inmates, we 
    don't try to file these with corrections agencies.
    </li>
    <li><b>Abuse</b><br />
    Submissions intended to harass OpenPolice.org, 
    its staff, partners, volunteers, or other users.
    </li>
    <li><b>Spam</b><br />
    Non-submissions generated by bots.
    </li>
    <li><b>Test</b><br />
    Non-submissions generated by people test-driving the complaint survey.
    </li>
    </ul>
</div>
