<!-- resources/views/vendor/openpolice/nodes/1712-report-inc-staff-tools-first-about-types.blade.php -->
<p><b>Police Complaint</b><br />
Every legitimate submission will receive our 
<a href="/web-app-workflows" target="_blank"
    ><i class="fa fa-external-link" aria-hidden="true"></i> primary OPC workflow</a>
and will be included in the site's main 
dataset. These must involve a specific incident, with attempts to identify officers 
from a specific law enforcement agency or private security force.</p>
<p><b>
The rest are submissions which do not describe an incident of misconduct 
by law enforcement agency or private security...
</b></p>
<ul>
<li><b>Not About Law Enforcement</b><br />
These submissions will not be filed anywhere for formal investigation, but will be published in a 
secondary anonymized dataset on OpenPolice.org. The complainant has the option to download their 
report and publish it on other websites. (OPC was carefully designed, but not to handle complaints 
focused on the CIA, NSA, paranormal activity, etc.)
</li>
<li><b>Abuse</b><br />
Non-submissions most intended to harass OpenPolice.org, it’s staff, partners, users, 
or participating officers.
</li>
<li><b>Spam</b><br />
Non-submissions most likely generated by robots.
</li>
<li><b>Test</b><br />
Non-submissions created by anyone just test-driving the complaint process.
</li>
<li><b>Not Sure</b><br />
If a complaint reviewer cannot decide how to best categorize the submission, 
this status will alert other reviewers for help.
</li>
</ul>