<!-- resources/views/vendor/openpolice/nodes/1712-report-inc-staff-tools-first-about-types.blade.php -->
<div class="mTn15 pB30">
    <p>
        <b>Police Complaint</b><br />
        Every submission describing a police incident goes 
        into the OpenPolice.org database. These should include 
        an incident time and place and at least one law enforcement 
        agency, officer, and misconduct allegation.
    </p>
    <p>
        <b>These are other common types of submissions.</b>
    </p>
    <ul>
    <li><b>Not About Law Enforcement</b><br />
    We don't file these submissions with police investigative agencies. 
    Instead, we store them in a secondary anonymized dataset on 
    OpenPolice.org. Common examples include complaints about 
    government service agencies or complaints related to 
    unidentified stalking or surveillance entities.
    </li>
    <li><b>Corrections Case</b><br />
    We don't file these submissions with prisons.
    </li>
    <li><b>Abuse</b><br />
    Submissions intended to harass OpenPolice.org, 
    its staff, partners, volunteers, or other users.
    </li>
    <li><b>Spam</b><br />
    Non-submissions generated by bots.
    </li>
    <li><b>Test</b><br />
    Non-submissions generated by people test-driving the complaint survey.
    </li>
    <li><b>Not Sure</b><br />
    If a complaint reviewer can't determine a suitable submission type, 
    this status alerts other reviewers for help.
    </li>
    </ul>
</div>
