
ALTER TABLE OP_AdminActions RENAME TO op_admin_actions;
ALTER TABLE OP_Administrators RENAME TO op_administrators;
ALTER TABLE OP_Allegations RENAME TO op_allegations;
ALTER TABLE OP_AllegSilver RENAME TO op_alleg_silver;
ALTER TABLE OP_Arrests RENAME TO op_arrests;
ALTER TABLE OP_BodyParts RENAME TO op_body_parts;
ALTER TABLE OP_Charges RENAME TO op_charges;
ALTER TABLE OP_CivCompliment RENAME TO op_civ_compliment;
ALTER TABLE OP_Civilians RENAME TO op_civilians;
ALTER TABLE OP_CivWeapons RENAME TO op_civ_weapons;
ALTER TABLE OP_ComplaintNotes RENAME TO op_complaint_notes;
ALTER TABLE OP_Complaints RENAME TO op_complaints;
ALTER TABLE OP_Compliments RENAME TO op_compliments;
ALTER TABLE OP_Departments RENAME TO op_departments;
ALTER TABLE OP_EventSequence RENAME TO op_event_sequence;
ALTER TABLE OP_Evidence RENAME TO op_evidence;
ALTER TABLE OP_EvidenceTime RENAME TO op_evidence_time;
ALTER TABLE OP_Force RENAME TO op_force;
ALTER TABLE OP_ForceBodyParts RENAME TO op_force_body_parts;
ALTER TABLE OP_ForceSubType RENAME TO op_force_sub_type;
ALTER TABLE OP_Incidents RENAME TO op_incidents;
ALTER TABLE OP_Injuries RENAME TO op_injuries;
ALTER TABLE OP_InjuryBodyParts RENAME TO op_injury_body_parts;
ALTER TABLE OP_InjuryCare RENAME TO op_injury_care;
ALTER TABLE OP_LinksCivilianAllegations RENAME TO op_links_civilian_allegations;
ALTER TABLE OP_LinksCivilianEvents RENAME TO op_links_civilian_events;
ALTER TABLE OP_LinksCivilianOrders RENAME TO op_links_civilian_orders;
ALTER TABLE OP_LinksCivilianVehicles RENAME TO op_links_civilian_vehicles;
ALTER TABLE OP_LinksComplaintDept RENAME TO op_links_complaint_dept;
ALTER TABLE OP_LinksComplaintOversight RENAME TO op_links_complaint_oversight;
ALTER TABLE OP_LinksComplimentDept RENAME TO op_links_compliment_dept;
ALTER TABLE OP_LinksComplimentOversight RENAME TO op_links_compliment_oversight;
ALTER TABLE OP_LinksOfficerAllegations RENAME TO op_links_officer_allegations;
ALTER TABLE OP_LinksOfficerDept RENAME TO op_links_officer_dept;
ALTER TABLE OP_LinksOfficerEvents RENAME TO op_links_officer_events;
ALTER TABLE OP_LinksOfficerOrders RENAME TO op_links_officer_orders;
ALTER TABLE OP_LinksOfficerVehicles RENAME TO op_links_officer_vehicles;
ALTER TABLE OP_OffCompliments RENAME TO op_off_compliments;
ALTER TABLE OP_Officers RENAME TO op_officers;
ALTER TABLE OP_OfficersVerified RENAME TO op_officers_verified;
ALTER TABLE OP_Orders RENAME TO op_orders;
ALTER TABLE OP_Oversight RENAME TO op_oversight;
ALTER TABLE OP_OversightModels RENAME TO op_oversight_models;
ALTER TABLE OP_PartnerCapac RENAME TO op_partner_capac;
ALTER TABLE OP_PartnerCaseTypes RENAME TO op_partner_case_types;
ALTER TABLE OP_PartnerFilters RENAME TO op_partner_filters;
ALTER TABLE OP_Partners RENAME TO op_partners;
ALTER TABLE OP_PartnerStates RENAME TO op_partner_states;
ALTER TABLE OP_PersonContact RENAME TO op_person_contact;
ALTER TABLE OP_PhysicalDesc RENAME TO op_physical_desc;
ALTER TABLE OP_PhysicalDescRace RENAME TO op_physical_desc_race;
ALTER TABLE OP_PrivilegeProfiles RENAME TO op_privilege_profiles;
ALTER TABLE OP_Scenes RENAME TO op_scenes;
ALTER TABLE OP_SearchContra RENAME TO op_search_contra;
ALTER TABLE OP_Searches RENAME TO op_searches;
ALTER TABLE OP_SearchSeize RENAME TO op_search_seize;
ALTER TABLE OP_StopReasons RENAME TO op_stop_reasons;
ALTER TABLE OP_Stops RENAME TO op_stops;
ALTER TABLE OP_Surveys RENAME TO op_surveys;
ALTER TABLE OP_TesterBeta RENAME TO op_tester_beta;
ALTER TABLE OP_Vehicles RENAME TO op_vehicles;
ALTER TABLE OP_Visitors RENAME TO op_visitors;
ALTER TABLE OP_zComplaintReviews RENAME TO op_z_complaint_reviews;
ALTER TABLE OP_Zedit_Departments RENAME TO op_z_edit_departments;
ALTER TABLE OP_Zedit_Oversight RENAME TO op_z_edit_oversight;
ALTER TABLE OP_zVolunStatDays RENAME TO op_z_volun_stat_days;
ALTER TABLE OP_zVolunTmp RENAME TO op_z_volun_tmp;
ALTER TABLE OP_zVolunUserInfo RENAME TO op_z_volun_user_info;

ALTER TABLE op_admin_actions CHANGE `AdmActID` `adm_act_id` int(11);
ALTER TABLE op_admin_actions CHANGE `AdmActUserID` `adm_act_user_id` bigint(20);
ALTER TABLE op_admin_actions CHANGE `AdmActTimestamp` `adm_act_timestamp` datetime;
ALTER TABLE op_admin_actions CHANGE `AdmActTable` `adm_act_table` varchar(255);
ALTER TABLE op_admin_actions CHANGE `AdmActRecordID` `adm_act_record_id` int(11);
ALTER TABLE op_admin_actions CHANGE `AdmActOldData` `adm_act_old_data` text;
ALTER TABLE op_admin_actions CHANGE `AdmActNewData` `adm_act_new_data` text;

ALTER TABLE op_administrators CHANGE `AdmID` `adm_id` int(11);
ALTER TABLE op_administrators CHANGE `AdmUserID` `adm_user_id` bigint(20);
ALTER TABLE op_administrators CHANGE `AdmPersonID` `adm_person_id` int(11);

ALTER TABLE op_allegations CHANGE `AlleID` `alle_id` int(11);
ALTER TABLE op_allegations CHANGE `AlleComplaintID` `alle_complaint_id` int(11);
ALTER TABLE op_allegations CHANGE `AlleType` `alle_type` int(11);
ALTER TABLE op_allegations CHANGE `AlleEventSequenceID` `alle_event_sequence_id` int(11);
ALTER TABLE op_allegations CHANGE `AlleDescription` `alle_description` text;
ALTER TABLE op_allegations CHANGE `AlleFindings` `alle_findings` int(11);

ALTER TABLE op_alleg_silver CHANGE `AlleSilID` `alle_sil_id` int(11);
ALTER TABLE op_alleg_silver CHANGE `AlleSilComplaintID` `alle_sil_complaint_id` int(11);
ALTER TABLE op_alleg_silver CHANGE `AlleSilStopYN` `alle_sil_stop_yn` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilStopWrongful` `alle_sil_stop_wrongful` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilOfficerID` `alle_sil_officer_id` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilOfficerRefuseID` `alle_sil_officer_refuse_id` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilSearchYN` `alle_sil_search_yn` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilSearchWrongful` `alle_sil_search_wrongful` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilWrongfulEntry` `alle_sil_wrongful_entry` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilForceYN` `alle_sil_force_yn` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilForceUnreason` `alle_sil_force_unreason` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilPropertyYN` `alle_sil_property_yn` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilPropertyWrongful` `alle_sil_property_wrongful` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilPropertyDamage` `alle_sil_property_damage` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilArrestYN` `alle_sil_arrest_yn` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilArrestWrongful` `alle_sil_arrest_wrongful` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilArrestRetaliatory` `alle_sil_arrest_retaliatory` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilArrestMiranda` `alle_sil_arrest_miranda` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilCitationYN` `alle_sil_citation_yn` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilCitationExcessive` `alle_sil_citation_excessive` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilProcedure` `alle_sil_procedure` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilNeglectDuty` `alle_sil_neglect_duty` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilBias` `alle_sil_bias` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilSexualHarass` `alle_sil_sexual_harass` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilSexualAssault` `alle_sil_sexual_assault` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilIntimidatingWeapon` `alle_sil_intimidating_weapon` int(11);
ALTER TABLE op_alleg_silver CHANGE `AlleSilIntimidatingWeaponType` `alle_sil_intimidating_weapon_type` int(11);
ALTER TABLE op_alleg_silver CHANGE `AlleSilRetaliation` `alle_sil_retaliation` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilRepeatContact` `alle_sil_repeat_contact` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilRepeatHarass` `alle_sil_repeat_harass` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilUnbecoming` `alle_sil_unbecoming` varchar(1);
ALTER TABLE op_alleg_silver CHANGE `AlleSilDiscourteous` `alle_sil_discourteous` varchar(1);

ALTER TABLE op_arrests CHANGE `ArstID` `arst_id` int(11);
ALTER TABLE op_arrests CHANGE `ArstEventSequenceID` `arst_event_sequence_id` int(11);
ALTER TABLE op_arrests CHANGE `ArstChargesFiled` `arst_charges_filed` varchar(1);
ALTER TABLE op_arrests CHANGE `ArstStatedReason` `arst_stated_reason` varchar(1);
ALTER TABLE op_arrests CHANGE `ArstStatedReasonDesc` `arst_stated_reason_desc` text;
ALTER TABLE op_arrests CHANGE `ArstMiranda` `arst_miranda` varchar(1);
ALTER TABLE op_arrests CHANGE `ArstSITA` `arst_sita` varchar(1);
ALTER TABLE op_arrests CHANGE `ArstChargesOther` `arst_charges_other` text;
ALTER TABLE op_arrests CHANGE `ArstNoChargesFiled` `arst_no_charges_filed` varchar(1);
ALTER TABLE op_arrests CHANGE `ArstStrip` `arst_strip` varchar(1);
ALTER TABLE op_arrests CHANGE `ArstStripSearchDesc` `arst_strip_search_desc` varchar(255);
ALTER TABLE op_arrests CHANGE `ArstAllegWrongfulArrest` `arst_alleg_wrongful_arrest` varchar(1);
ALTER TABLE op_arrests CHANGE `ArstAllegRetaliatoryCharges` `arst_alleg_retaliatory_charges` varchar(1);

ALTER TABLE op_body_parts CHANGE `BodyID` `body_id` int(11);
ALTER TABLE op_body_parts CHANGE `BodyForceID` `body_force_id` int(11);
ALTER TABLE op_body_parts CHANGE `BodyInjuryID` `body_injury_id` int(11);
ALTER TABLE op_body_parts CHANGE `BodyPart` `body_part` int(11);

ALTER TABLE op_charges CHANGE `ChrgID` `chrg_id` int(11);
ALTER TABLE op_charges CHANGE `ChrgCivID` `chrg_civ_id` int(11);
ALTER TABLE op_charges CHANGE `ChrgEventID` `chrg_event_id` int(11);
ALTER TABLE op_charges CHANGE `ChrgCharges` `chrg_charges` int(11);

ALTER TABLE op_civ_compliment CHANGE `CivCompID` `civ_comp_id` int(11);
ALTER TABLE op_civ_compliment CHANGE `CivCompComplimentID` `civ_comp_compliment_id` int(11);
ALTER TABLE op_civ_compliment CHANGE `CivCompUserID` `civ_comp_user_id` int(11);
ALTER TABLE op_civ_compliment CHANGE `CivCompIsCreator` `civ_comp_is_creator` varchar(1);
ALTER TABLE op_civ_compliment CHANGE `CivCompRole` `civ_comp_role` varchar(10);
ALTER TABLE op_civ_compliment CHANGE `CivCompPersonID` `civ_comp_person_id` int(11);
ALTER TABLE op_civ_compliment CHANGE `CivCompPhysDescID` `civ_comp_phys_desc_id` int(11);

ALTER TABLE op_civilians CHANGE `CivID` `civ_id` int(11);
ALTER TABLE op_civilians CHANGE `CivComplaintID` `civ_complaint_id` int(11);
ALTER TABLE op_civilians CHANGE `CivVictimUseWeapon` `civ_victim_use_weapon` int(11);
ALTER TABLE op_civilians CHANGE `CivVictimHadWeapon` `civ_victim_had_weapon` varchar(1);
ALTER TABLE op_civilians CHANGE `CivVictimWhatWeapon` `civ_victim_what_weapon` int(11);
ALTER TABLE op_civilians CHANGE `CivUserID` `civ_user_id` bigint(20);
ALTER TABLE op_civilians CHANGE `CivIsCreator` `civ_is_creator` varchar(1);
ALTER TABLE op_civilians CHANGE `CivRole` `civ_role` varchar(10);
ALTER TABLE op_civilians CHANGE `CivPersonID` `civ_person_id` int(11);
ALTER TABLE op_civilians CHANGE `CivPhysDescID` `civ_phys_desc_id` int(11);
ALTER TABLE op_civilians CHANGE `CivGiveName` `civ_give_name` varchar(1);
ALTER TABLE op_civilians CHANGE `CivGiveContactInfo` `civ_give_contact_info` varchar(1);
ALTER TABLE op_civilians CHANGE `CivGivePhysDesc` `civ_give_phys_desc` varchar(1);
ALTER TABLE op_civilians CHANGE `CivHadVehicle` `civ_had_vehicle` varchar(1);
ALTER TABLE op_civilians CHANGE `CivChase` `civ_chase` varchar(1);
ALTER TABLE op_civilians CHANGE `CivInPreviousVehicle` `civ_in_previous_vehicle` varchar(1);
ALTER TABLE op_civilians CHANGE `CivResident` `civ_resident` varchar(1);
ALTER TABLE op_civilians CHANGE `CivChaseType` `civ_chase_type` int(11);
ALTER TABLE op_civilians CHANGE `CivCameraRecord` `civ_camera_record` varchar(1);
ALTER TABLE op_civilians CHANGE `CivUsedProfanity` `civ_used_profanity` varchar(1);
ALTER TABLE op_civilians CHANGE `CivOccupation` `civ_occupation` varchar(255);
ALTER TABLE op_civilians CHANGE `CivGivenCitation` `civ_given_citation` varchar(1);
ALTER TABLE op_civilians CHANGE `CivGivenWarning` `civ_given_warning` varchar(1);
ALTER TABLE op_civilians CHANGE `CivHasInjury` `civ_has_injury` varchar(1);
ALTER TABLE op_civilians CHANGE `CivHasInjuryCare` `civ_has_injury_care` varchar(1);
ALTER TABLE op_civilians CHANGE `CivCitationNumber` `civ_citation_number` varchar(255);
ALTER TABLE op_civilians CHANGE `CivChargesOther` `civ_charges_other` text;

ALTER TABLE op_civ_weapons CHANGE `CivWeapID` `civ_weap_id` int(11);
ALTER TABLE op_civ_weapons CHANGE `CivWeapComID` `civ_weap_com_id` int(11);
ALTER TABLE op_civ_weapons CHANGE `CivWeapBodyWeapon` `civ_weap_body_weapon` int(11);

ALTER TABLE op_complaint_notes CHANGE `NoteID` `note_id` int(11);
ALTER TABLE op_complaint_notes CHANGE `NoteComplaintID` `note_complaint_id` int(11);
ALTER TABLE op_complaint_notes CHANGE `NoteUserID` `note_user_id` bigint(20);
ALTER TABLE op_complaint_notes CHANGE `NoteTimestamp` `note_timestamp` datetime;
ALTER TABLE op_complaint_notes CHANGE `NoteContent` `note_content` text;

ALTER TABLE op_complaints CHANGE `ComID` `com_id` int(11);
ALTER TABLE op_complaints CHANGE `ComPublicID` `com_public_id` int(11);
ALTER TABLE op_complaints CHANGE `ComUserID` `com_user_id` bigint(20);
ALTER TABLE op_complaints CHANGE `ComStatus` `com_status` int(11);
ALTER TABLE op_complaints CHANGE `ComType` `com_type` int(11);
ALTER TABLE op_complaints CHANGE `ComIsDemo` `com_is_demo` tinyint(1);
ALTER TABLE op_complaints CHANGE `ComIncidentID` `com_incident_id` int(11);
ALTER TABLE op_complaints CHANGE `ComSceneID` `com_scene_id` int(11);
ALTER TABLE op_complaints CHANGE `ComPrivacy` `com_privacy` int(11);
ALTER TABLE op_complaints CHANGE `ComAwardMedallion` `com_award_medallion` varchar(10);
ALTER TABLE op_complaints CHANGE `ComSummary` `com_summary` text;
ALTER TABLE op_complaints CHANGE `ComAllegList` `com_alleg_list` text;
ALTER TABLE op_complaints CHANGE `ComTriedOtherWays` `com_tried_other_ways` varchar(1);
ALTER TABLE op_complaints CHANGE `ComTriedOtherWaysDesc` `com_tried_other_ways_desc` varchar(255);
ALTER TABLE op_complaints CHANGE `ComOfficerInjured` `com_officer_injured` varchar(1);
ALTER TABLE op_complaints CHANGE `ComOfficerInjuredDesc` `com_officer_injured_desc` varchar(255);
ALTER TABLE op_complaints CHANGE `ComAttorneyHas` `com_attorney_has` varchar(1);
ALTER TABLE op_complaints CHANGE `ComAttorneyOKedOPC` `com_attorney_oked` varchar(1);
ALTER TABLE op_complaints CHANGE `ComAttorneyWant` `com_attorney_want` varchar(1);
ALTER TABLE op_complaints CHANGE `ComAnyoneCharged` `com_anyone_charged` varchar(1);
ALTER TABLE op_complaints CHANGE `ComAllChargesResolved` `com_all_charges_resolved` varchar(1);
ALTER TABLE op_complaints CHANGE `ComUnresolvedChargesActions` `com_unresolved_charges_actions` int(11);
ALTER TABLE op_complaints CHANGE `ComFileLawsuit` `com_file_lawsuit` varchar(1);
ALTER TABLE op_complaints CHANGE `ComLegalAidHelp` `com_legal_aid_help` varchar(255);
ALTER TABLE op_complaints CHANGE `ComGovtInvestigation` `com_govt_investigation` varchar(1);
ALTER TABLE op_complaints CHANGE `ComGovtInvestigationWhyNot` `com_govt_investigation_why_not` varchar(255);
ALTER TABLE op_complaints CHANGE `ComHowHear` `com_how_hear` varchar(255);
ALTER TABLE op_complaints CHANGE `ComFeedback` `com_feedback` text;
ALTER TABLE op_complaints CHANGE `ComOfficerDisciplined` `com_officer_disciplined` varchar(1);
ALTER TABLE op_complaints CHANGE `ComOfficerDisciplineType` `com_officer_disciplined_type` text;
ALTER TABLE op_complaints CHANGE `ComMediaLinks` `com_media_links` text;
ALTER TABLE op_complaints CHANGE `ComAdminID` `com_admin_id` int(11);
ALTER TABLE op_complaints CHANGE `ComAttID` `com_att_id` int(11);
ALTER TABLE op_complaints CHANGE `ComNotes` `com_notes` text;
ALTER TABLE op_complaints CHANGE `ComSlug` `com_slug` varchar(255);
ALTER TABLE op_complaints CHANGE `ComRecordSubmitted` `com_record_submitted` datetime;
ALTER TABLE op_complaints CHANGE `ComSubmissionProgress` `com_submission_progress` varchar(255);
ALTER TABLE op_complaints CHANGE `ComVersionAB` `com_version_ab` varchar(255);
ALTER TABLE op_complaints CHANGE `ComTreeVersion` `com_tree_version` varchar(50);
ALTER TABLE op_complaints CHANGE `ComHoneyPot` `com_honey_pot` varchar(255);
ALTER TABLE op_complaints CHANGE `ComIsMobile` `com_is_mobile` tinyint(1);
ALTER TABLE op_complaints CHANGE `ComUniqueStr` `com_unique_str` varchar(20);
ALTER TABLE op_complaints CHANGE `ComIPaddy` `com_ip_addy` varchar(255);
ALTER TABLE op_complaints CHANGE `ComShareData` `com_share_data` tinyint(1);

ALTER TABLE op_compliments CHANGE `CompliID` `compli_id` int(11);
ALTER TABLE op_compliments CHANGE `CompliPublicID` `compli_public_id` int(11);
ALTER TABLE op_compliments CHANGE `CompliUserID` `compli_user_id` bigint(20);
ALTER TABLE op_compliments CHANGE `CompliStatus` `compli_status` int(11);
ALTER TABLE op_compliments CHANGE `CompliType` `compli_type` int(11);
ALTER TABLE op_compliments CHANGE `CompliIsDemo` `compli_is_demo` tinyint(1);
ALTER TABLE op_compliments CHANGE `CompliIncidentID` `compli_incident_id` int(11);
ALTER TABLE op_compliments CHANGE `CompliSceneID` `compli_scene_id` int(11);
ALTER TABLE op_compliments CHANGE `CompliPrivacy` `compli_privacy` int(11);
ALTER TABLE op_compliments CHANGE `CompliSummary` `compli_summary` text;
ALTER TABLE op_compliments CHANGE `CompliHowHear` `compli_how_hear` varchar(255);
ALTER TABLE op_compliments CHANGE `CompliFeedback` `compli_feedback` text;
ALTER TABLE op_compliments CHANGE `CompliSlug` `compli_slug` varchar(255);
ALTER TABLE op_compliments CHANGE `CompliNotes` `compli_notes` text;
ALTER TABLE op_compliments CHANGE `CompliRecordSubmitted` `compli_record_submitted` datetime;
ALTER TABLE op_compliments CHANGE `CompliSubmissionProgress` `compli_submission_progress` varchar(255);
ALTER TABLE op_compliments CHANGE `CompliVersionAB` `compli_version_ab` varchar(255);
ALTER TABLE op_compliments CHANGE `CompliTreeVersion` `compli_tree_version` varchar(50);
ALTER TABLE op_compliments CHANGE `CompliHoneyPot` `compli_honey_pot` varchar(255);
ALTER TABLE op_compliments CHANGE `CompliIsMobile` `compli_is_mobile` tinyint(1);
ALTER TABLE op_compliments CHANGE `CompliUniqueStr` `compli_unique_str` varchar(20);
ALTER TABLE op_compliments CHANGE `CompliIPaddy` `compli_ip_addy` varchar(255);
ALTER TABLE op_compliments CHANGE `CompliShareData` `compli_share_data` tinyint(1);

ALTER TABLE op_departments CHANGE `DeptID` `dept_id` int(11);
ALTER TABLE op_departments CHANGE `DeptName` `dept_name` varchar(255);
ALTER TABLE op_departments CHANGE `DeptSlug` `dept_slug` varchar(100);
ALTER TABLE op_departments CHANGE `DeptType` `dept_type` int(11);
ALTER TABLE op_departments CHANGE `DeptStatus` `dept_status` int(11);
ALTER TABLE op_departments CHANGE `DeptVerified` `dept_verified` datetime;
ALTER TABLE op_departments CHANGE `DeptEmail` `dept_email` varchar(255);
ALTER TABLE op_departments CHANGE `DeptPhoneWork` `dept_phone_work` varchar(20);
ALTER TABLE op_departments CHANGE `DeptAddress` `dept_address` varchar(255);
ALTER TABLE op_departments CHANGE `DeptAddress2` `dept_address2` varchar(255);
ALTER TABLE op_departments CHANGE `DeptAddressCity` `dept_address_city` varchar(255);
ALTER TABLE op_departments CHANGE `DeptAddressState` `dept_address_state` varchar(2);
ALTER TABLE op_departments CHANGE `DeptAddressZip` `dept_address_zip` varchar(10);
ALTER TABLE op_departments CHANGE `DeptAddressCounty` `dept_address_county` varchar(100);
ALTER TABLE op_departments CHANGE `DeptAddressLat` `dept_address_lat` double;
ALTER TABLE op_departments CHANGE `DeptAddressLng` `dept_address_lng` double;
ALTER TABLE op_departments CHANGE `DeptScoreOpenness` `dept_score_openness` int(11);
ALTER TABLE op_departments CHANGE `DeptTotOfficers` `dept_tot_officers` int(11);
ALTER TABLE op_departments CHANGE `DeptJurisdictionPopulation` `dept_jurisdiction_population` int(11);
ALTER TABLE op_departments CHANGE `DeptJurisdictionGPS` `dept_jurisdiction_gps` text;
ALTER TABLE op_departments CHANGE `DeptVersionAB` `dept_version_ab` varchar(255);
ALTER TABLE op_departments CHANGE `DeptSubmissionProgress` `dept_submission_progress` int(11);
ALTER TABLE op_departments CHANGE `DeptIPaddy` `dept_ip_addy` varchar(255);
ALTER TABLE op_departments CHANGE `DeptTreeVersion` `dept_tree_version` varchar(255);
ALTER TABLE op_departments CHANGE `DeptUniqueStr` `dept_unique_str` varchar(255);
ALTER TABLE op_departments CHANGE `DeptUserID` `dept_user_id` bigint(20);
ALTER TABLE op_departments CHANGE `DeptIsMobile` `dept_is_mobile` varchar(255);

ALTER TABLE op_event_sequence CHANGE `EveID` `eve_id` int(11);
ALTER TABLE op_event_sequence CHANGE `EveComplaintID` `eve_complaint_id` int(11);
ALTER TABLE op_event_sequence CHANGE `EveOrder` `eve_order` int(11);
ALTER TABLE op_event_sequence CHANGE `EveType` `eve_type` varchar(255);
ALTER TABLE op_event_sequence CHANGE `EveUserFinished` `eve_user_finished` varchar(255);

ALTER TABLE op_evidence CHANGE `EvidID` `evid_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidComplaintID` `evid_complaint_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidComplimentID` `evid_compliment_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidType` `evid_type` int(11);
ALTER TABLE op_evidence CHANGE `EvidPrivacy` `evid_privacy` varchar(10);
ALTER TABLE op_evidence CHANGE `EvidDateTime` `evid_date_time` date;
ALTER TABLE op_evidence CHANGE `EvidTitle` `evid_title` varchar(255);
ALTER TABLE op_evidence CHANGE `EvidEvidenceDesc` `evid_evidence_desc` text;
ALTER TABLE op_evidence CHANGE `EvidUploadFile` `evid_upload_file` varchar(255);
ALTER TABLE op_evidence CHANGE `EvidStoredFile` `evid_stored_file` varchar(30);
ALTER TABLE op_evidence CHANGE `EvidVideoLink` `evid_video_link` varchar(255);
ALTER TABLE op_evidence CHANGE `EvidVideoDuration` `evid_video_duration` int(11);
ALTER TABLE op_evidence CHANGE `EvidCivilianID` `evid_civilian_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidDeptID` `evid_dept_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidSceneID` `evid_scene_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidEventSequenceID` `evid_event_sequence_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidInjuryID` `evid_injury_id` int(11);
ALTER TABLE op_evidence CHANGE `EvidNoteID` `evid_note_id` int(11);

ALTER TABLE op_evidence_time CHANGE `EviTimID` `evi_tim_id` int(11);
ALTER TABLE op_evidence_time CHANGE `EviTimAllegationID` `evi_tim_allegation_id` int(11);
ALTER TABLE op_evidence_time CHANGE `EviTimEvidenceID` `evi_tim_evidence_id` int(11);
ALTER TABLE op_evidence_time CHANGE `EviTimTimestamp` `evi_tim_timestamp` int(11);
ALTER TABLE op_evidence_time CHANGE `EviTimDescription` `evi_tim_description` varchar(255);

ALTER TABLE op_force CHANGE `ForID` `for_id` int(11);
ALTER TABLE op_force CHANGE `ForEventSequenceID` `for_event_sequence_id` int(11);
ALTER TABLE op_force CHANGE `ForAgainstAnimal` `for_against_animal` varchar(1);
ALTER TABLE op_force CHANGE `ForAnimalDesc` `for_animal_desc` varchar(255);
ALTER TABLE op_force CHANGE `ForType` `for_type` int(11);
ALTER TABLE op_force CHANGE `ForTypeOther` `for_type_other` varchar(255);
ALTER TABLE op_force CHANGE `ForGunAmmoType` `for_gun_ammo_type` int(11);
ALTER TABLE op_force CHANGE `ForGunDesc` `for_gun_desc` varchar(255);
ALTER TABLE op_force CHANGE `ForHowManyTimes` `for_how_many_times` int(11);
ALTER TABLE op_force CHANGE `ForOrdersBeforeForce` `for_orders_before_force` varchar(1);
ALTER TABLE op_force CHANGE `ForOrdersSubjectResponse` `for_orders_subject_response` text;
ALTER TABLE op_force CHANGE `ForWhileHandcuffed` `for_while_handcuffed` varchar(1);
ALTER TABLE op_force CHANGE `ForWhileHeldDown` `for_while_held_down` varchar(1);
ALTER TABLE op_force CHANGE `ForAllegUnreasonable` `for_alleg_unreasonable` varchar(1);

ALTER TABLE op_force_body_parts CHANGE `FrcBdyID` `frc_bdy_id` int(11);
ALTER TABLE op_force_body_parts CHANGE `FrcBdyForceID` `frc_bdy_force_id` int(11);
ALTER TABLE op_force_body_parts CHANGE `FrcBdyPart` `frc_bdy_part` int(11);

ALTER TABLE op_force_sub_type CHANGE `ForceSubID` `force_sub_id` int(11);
ALTER TABLE op_force_sub_type CHANGE `ForceSubForceID` `force_sub_force_id` int(11);
ALTER TABLE op_force_sub_type CHANGE `ForceSubType` `force_sub_type` int(11);

ALTER TABLE op_incidents CHANGE `IncID` `inc_id` int(11);
ALTER TABLE op_incidents CHANGE `IncComplaintID` `inc_complaint_id` int(11);
ALTER TABLE op_incidents CHANGE `IncAddress` `inc_address` varchar(255);
ALTER TABLE op_incidents CHANGE `IncAddress2` `inc_address2` varchar(255);
ALTER TABLE op_incidents CHANGE `IncAddressCity` `inc_address_city` varchar(255);
ALTER TABLE op_incidents CHANGE `IncAddressState` `inc_address_state` varchar(2);
ALTER TABLE op_incidents CHANGE `IncAddressZip` `inc_address_zip` varchar(10);
ALTER TABLE op_incidents CHANGE `IncAddressLat` `inc_address_lat` double;
ALTER TABLE op_incidents CHANGE `IncAddressLng` `inc_address_lng` double;
ALTER TABLE op_incidents CHANGE `IncLandmarks` `inc_landmarks` varchar(255);
ALTER TABLE op_incidents CHANGE `IncDate` `inc_date` date;
ALTER TABLE op_incidents CHANGE `IncTimeStart` `inc_time_start` datetime;
ALTER TABLE op_incidents CHANGE `IncTimeEnd` `inc_time_end` datetime;
ALTER TABLE op_incidents CHANGE `IncDuration` `inc_duration` int(11);
ALTER TABLE op_incidents CHANGE `IncPublic` `inc_public` tinyint(1);

ALTER TABLE op_injuries CHANGE `InjID` `inj_id` int(11);
ALTER TABLE op_injuries CHANGE `InjSubjectID` `inj_subject_id` int(11);
ALTER TABLE op_injuries CHANGE `InjType` `inj_type` int(11);
ALTER TABLE op_injuries CHANGE `InjHowManyTimes` `inj_how_many_times` int(11);
ALTER TABLE op_injuries CHANGE `InjDescription` `inj_description` text;
ALTER TABLE op_injuries CHANGE `InjDone` `inj_done` tinyint(1);

ALTER TABLE op_injury_body_parts CHANGE `InjBdyID` `inj_bdy_id` int(11);
ALTER TABLE op_injury_body_parts CHANGE `InjBdyInjuryID` `inj_bdy_injury_id` int(11);
ALTER TABLE op_injury_body_parts CHANGE `InjBdyPart` `inj_bdy_part` int(11);

ALTER TABLE op_injury_care CHANGE `InjCareID` `inj_care_id` int(11);
ALTER TABLE op_injury_care CHANGE `InjCareSubjectID` `inj_care_subject_id` int(11);
ALTER TABLE op_injury_care CHANGE `InjCareResultInDeath` `inj_care_result_in_death` varchar(1);
ALTER TABLE op_injury_care CHANGE `InjCareTimeOfDeath` `inj_care_time_of_death` datetime;
ALTER TABLE op_injury_care CHANGE `InjCareGotMedical` `inj_care_got_medical` varchar(1);
ALTER TABLE op_injury_care CHANGE `InjCareHospitalTreated` `inj_care_hospital_treated` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareDoctorNameFirst` `inj_care_doctor_name_first` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareDoctorNameLast` `inj_care_doctor_name_last` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareDoctorEmail` `inj_care_doctor_email` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareDoctorPhone` `inj_care_doctor_phone` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareEmergencyOnScene` `inj_care_emergency_on_scene` varchar(1);
ALTER TABLE op_injury_care CHANGE `InjCareEmergencyNameFirst` `inj_care_emergency_name_first` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareEmergencyNameLast` `inj_care_emergency_name_last` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareEmergencyIDnumber` `inj_care_emergency_id_number` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareEmergencyVehicleNumber` `inj_care_emergency_vehicle_number` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareEmergencyLicenceNumber` `inj_care_emergency_licence_number` varchar(255);
ALTER TABLE op_injury_care CHANGE `InjCareEmergencyDeptName` `inj_care_emergency_dept_name` varchar(255);

ALTER TABLE op_links_civilian_allegations CHANGE `LnkCivAlleID` `lnk_civ_alle_id` int(11);
ALTER TABLE op_links_civilian_allegations CHANGE `LnkCivAlleCivID` `lnk_civ_alle_civ_id` int(11);
ALTER TABLE op_links_civilian_allegations CHANGE `LnkCivAlleAlleID` `lnk_civ_alle_alle_id` int(11);

ALTER TABLE op_links_civilian_events CHANGE `LnkCivEveID` `lnk_civ_eve_id` int(11);
ALTER TABLE op_links_civilian_events CHANGE `LnkCivEveCivID` `lnk_civ_eve_civ_id` int(11);
ALTER TABLE op_links_civilian_events CHANGE `LnkCivEveEveID` `lnk_civ_eve_eve_id` int(11);

ALTER TABLE op_links_civilian_orders CHANGE `LnkCivOrdID` `lnk_civ_ord_id` int(11);
ALTER TABLE op_links_civilian_orders CHANGE `LnkCivOrdCivID` `lnk_civ_ord_civ_id` int(11);
ALTER TABLE op_links_civilian_orders CHANGE `LnkCivOrdOrdID` `lnk_civ_ord_ord_id` int(11);

ALTER TABLE op_links_civilian_vehicles CHANGE `LnkCivVehicID` `lnk_civ_vehic_id` int(11);
ALTER TABLE op_links_civilian_vehicles CHANGE `LnkCivVehicCivID` `lnk_civ_vehic_civ_id` int(11);
ALTER TABLE op_links_civilian_vehicles CHANGE `LnkCivVehicVehicID` `lnk_civ_vehic_vehic_id` int(11);
ALTER TABLE op_links_civilian_vehicles CHANGE `LnkCivVehicRole` `lnk_civ_vehic_role` int(11);

ALTER TABLE op_links_complaint_dept CHANGE `LnkComDeptID` `lnk_com_dept_id` int(11);
ALTER TABLE op_links_complaint_dept CHANGE `LnkComDeptComplaintID` `lnk_com_dept_complaint_id` int(11);
ALTER TABLE op_links_complaint_dept CHANGE `LnkComDeptDeptID` `lnk_com_dept_dept_id` int(11);

ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverID` `lnk_com_over_id` int(11);
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverComplaintID` `lnk_com_over_complaint_id` int(11);
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverDeptID` `lnk_com_over_dept_id` int(11);
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverOverID` `lnk_com_over_over_id` int(11);
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverSubmitted` `lnk_com_over_submitted` datetime;
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverStillNoResponse` `lnk_com_over_still_no_response` datetime;
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverReceived` `lnk_com_over_received` datetime;
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverInvestigated` `lnk_com_over_investigated` datetime;
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverReportDate` `lnk_com_over_report_date` datetime;
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverOversightReportEvidenceID` `lnk_com_over_oversight_report_evidence_id` int(11);
ALTER TABLE op_links_complaint_oversight CHANGE `LnkComOverAgencyComplaintNumber` `lnk_com_over_agency_complaint_number` int(11);

ALTER TABLE op_links_compliment_dept CHANGE `LnkCompliDeptID` `lnk_compli_dept_id` int(11);
ALTER TABLE op_links_compliment_dept CHANGE `LnkCompliDeptComplimentID` `lnk_compli_dept_compliment_id` int(11);
ALTER TABLE op_links_compliment_dept CHANGE `LnkCompliDeptDeptID` `lnk_compli_dept_dept_id` int(11);

ALTER TABLE op_links_compliment_oversight CHANGE `LnkCompliOverID` `lnk_compli_over_id` int(11);
ALTER TABLE op_links_compliment_oversight CHANGE `LnkCompliOverComplimentID` `lnk_compli_over_compliment_id` int(11);
ALTER TABLE op_links_compliment_oversight CHANGE `LnkCompliOverDeptID` `lnk_compli_over_dept_id` int(11);
ALTER TABLE op_links_compliment_oversight CHANGE `LnkCompliOverOverID` `lnk_compli_over_over_id` int(11);
ALTER TABLE op_links_compliment_oversight CHANGE `LnkCompliOverSubmitted` `lnk_compli_over_submitted` datetime;
ALTER TABLE op_links_compliment_oversight CHANGE `LnkCompliOverReceived` `lnk_compli_over_received` datetime;

ALTER TABLE op_links_officer_allegations CHANGE `LnkOffAlleID` `lnk_off_alle_id` int(11);
ALTER TABLE op_links_officer_allegations CHANGE `LnkOffAlleOffID` `lnk_off_alle_off_id` int(11);
ALTER TABLE op_links_officer_allegations CHANGE `LnkOffAlleAlleID` `lnk_off_alle_alle_id` int(11);

ALTER TABLE op_links_officer_dept CHANGE `LnkOffDeptID` `lnk_off_dept_id` int(11);
ALTER TABLE op_links_officer_dept CHANGE `LnkOffDeptOfficerID` `lnk_off_dept_officer_id` int(11);
ALTER TABLE op_links_officer_dept CHANGE `LnkOffDeptDeptID` `lnk_off_dept_dept_id` int(11);
ALTER TABLE op_links_officer_dept CHANGE `LnkOffDeptDateVerified` `lnk_off_dept_date_verified` date;

ALTER TABLE op_links_officer_events CHANGE `LnkOffEveID` `lnk_off_eve_id` int(11);
ALTER TABLE op_links_officer_events CHANGE `LnkOffEveOffID` `lnk_off_eve_off_id` int(11);
ALTER TABLE op_links_officer_events CHANGE `LnkOffEveEveID` `lnk_off_eve_eve_id` int(11);

ALTER TABLE op_links_officer_orders CHANGE `LnkOffOrdID` `lnk_off_ord_id` int(11);
ALTER TABLE op_links_officer_orders CHANGE `LnkOffOrdOffID` `lnk_off_ord_off_id` int(11);
ALTER TABLE op_links_officer_orders CHANGE `LnkOffOrdOrdID` `lnk_off_ord_ord_id` int(11);

ALTER TABLE op_links_officer_vehicles CHANGE `LnkOffVehicID` `lnk_off_vehic_id` int(11);
ALTER TABLE op_links_officer_vehicles CHANGE `LnkOffVehicOffID` `lnk_off_vehic_off_id` int(11);
ALTER TABLE op_links_officer_vehicles CHANGE `LnkOffVehicVehicID` `lnk_off_vehic_vehic_id` int(11);
ALTER TABLE op_links_officer_vehicles CHANGE `LnkOffVehicRole` `lnk_off_vehic_role` int(11);

ALTER TABLE op_off_compliments CHANGE `OffCompID` `off_comp_id` int(11);
ALTER TABLE op_off_compliments CHANGE `OffCompComplimentID` `off_comp_compliment_id` int(11);
ALTER TABLE op_off_compliments CHANGE `OffCompOffID` `off_comp_off_id` int(11);
ALTER TABLE op_off_compliments CHANGE `OffCompValor` `off_comp_valor` varchar(1);
ALTER TABLE op_off_compliments CHANGE `OffCompLifesaving` `off_comp_lifesaving` varchar(1);
ALTER TABLE op_off_compliments CHANGE `OffCompDeescalation` `off_comp_deescalation` varchar(1);
ALTER TABLE op_off_compliments CHANGE `OffCompProfessionalism` `off_comp_professionalism` varchar(1);
ALTER TABLE op_off_compliments CHANGE `OffCompFairness` `off_comp_fairness` varchar(1);
ALTER TABLE op_off_compliments CHANGE `OffCompConstitutional` `off_comp_constitutional` varchar(1);
ALTER TABLE op_off_compliments CHANGE `OffCompCompassion` `off_comp_compassion` varchar(1);
ALTER TABLE op_off_compliments CHANGE `OffCompCommunity` `off_comp_community` varchar(1);

ALTER TABLE op_officers CHANGE `OffID` `off_id` int(11);
ALTER TABLE op_officers CHANGE `OffVerifiedID` `off_verified_id` int(11);
ALTER TABLE op_officers CHANGE `OffComplaintID` `off_complaint_id` int(11);
ALTER TABLE op_officers CHANGE `OffRole` `off_role` varchar(255);
ALTER TABLE op_officers CHANGE `OffDeptID` `off_dept_id` int(11);
ALTER TABLE op_officers CHANGE `OffPersonID` `off_person_id` int(11);
ALTER TABLE op_officers CHANGE `OffPhysDescID` `off_phys_desc_id` int(11);
ALTER TABLE op_officers CHANGE `OffGiveName` `off_give_name` varchar(1);
ALTER TABLE op_officers CHANGE `OffGivePhysDesc` `off_give_phys_desc` varchar(1);
ALTER TABLE op_officers CHANGE `OffHadVehicle` `off_had_vehicle` varchar(1);
ALTER TABLE op_officers CHANGE `OffInPreviousVehicle` `off_in_previous_vehicle` varchar(1);
ALTER TABLE op_officers CHANGE `OffPrecinct` `off_precinct` varchar(255);
ALTER TABLE op_officers CHANGE `OffBadgeNumber` `off_badge_number` int(11);
ALTER TABLE op_officers CHANGE `OffIDnumber` `off_id_number` int(11);
ALTER TABLE op_officers CHANGE `OffOfficerRank` `off_officer_rank` varchar(255);
ALTER TABLE op_officers CHANGE `OffDashCam` `off_dash_cam` varchar(1);
ALTER TABLE op_officers CHANGE `OffBodyCam` `off_body_cam` varchar(1);
ALTER TABLE op_officers CHANGE `OffDutyStatus` `off_duty_status` varchar(10);
ALTER TABLE op_officers CHANGE `OffUniform` `off_uniform` varchar(1);
ALTER TABLE op_officers CHANGE `OffUsedProfanity` `off_used_profanity` varchar(1);
ALTER TABLE op_officers CHANGE `OffAdditionalDetails` `off_additional_details` text;
ALTER TABLE op_officers CHANGE `OffGaveCompliment` `off_gave_compliment` varchar(1);

ALTER TABLE op_officers_verified CHANGE `OffVerID` `off_ver_id` int(11);
ALTER TABLE op_officers_verified CHANGE `OffVerStatus` `off_ver_status` int(11);
ALTER TABLE op_officers_verified CHANGE `OffVerPersonID` `off_ver_person_id` int(11);
ALTER TABLE op_officers_verified CHANGE `OffVerCntComplaints` `off_ver_cnt_complaints` int(11);
ALTER TABLE op_officers_verified CHANGE `OffVerCntAllegations` `off_ver_cnt_allegations` int(11);
ALTER TABLE op_officers_verified CHANGE `OffVerUniqueStr` `off_ver_unique_str` varchar(255);
ALTER TABLE op_officers_verified CHANGE `OffVerSubmissionProgress` `off_ver_submission_progress` int(11);
ALTER TABLE op_officers_verified CHANGE `OffVerVersionAB` `off_ver_version_ab` varchar(255);
ALTER TABLE op_officers_verified CHANGE `OffVerTreeVersion` `off_ver_tree_version` varchar(255);
ALTER TABLE op_officers_verified CHANGE `OffVerIPaddy` `off_ver_ip_addy` varchar(255);
ALTER TABLE op_officers_verified CHANGE `OffVerIsMobile` `off_ver_is_mobile` varchar(255);
ALTER TABLE op_officers_verified CHANGE `OffVerUserID` `off_ver_user_id` bigint(20);
ALTER TABLE op_officers_verified CHANGE `OffVerCntCompliments` `off_ver_cnt_compliments` int(11);
ALTER TABLE op_officers_verified CHANGE `OffVerCntCommends` `off_ver_cnt_commends` int(11);

ALTER TABLE op_orders CHANGE `OrdID` `ord_id` int(11);
ALTER TABLE op_orders CHANGE `OrdEventSequenceID` `ord_event_sequence_id` int(11);
ALTER TABLE op_orders CHANGE `OrdDescription` `ord_description` text;
ALTER TABLE op_orders CHANGE `OrdTroubleUnderYN` `ord_trouble_under_yn` varchar(1);
ALTER TABLE op_orders CHANGE `OrdTroubleUnderstading` `ord_trouble_understading` varchar(255);

ALTER TABLE op_oversight CHANGE `OverID` `over_id` int(11);
ALTER TABLE op_oversight CHANGE `OverType` `over_type` int(11);
ALTER TABLE op_oversight CHANGE `OverCivModel` `over_civ_model` int(11);
ALTER TABLE op_oversight CHANGE `OverUserID` `over_user_id` bigint(20);
ALTER TABLE op_oversight CHANGE `OverDeptID` `over_dept_id` int(11);
ALTER TABLE op_oversight CHANGE `OverAgncName` `over_agnc_name` varchar(255);
ALTER TABLE op_oversight CHANGE `OverVerified` `over_verified` datetime;
ALTER TABLE op_oversight CHANGE `OverNamePrefix` `over_name_prefix` varchar(20);
ALTER TABLE op_oversight CHANGE `OverNameFirst` `over_name_first` varchar(255);
ALTER TABLE op_oversight CHANGE `OverNickname` `over_nickname` varchar(255);
ALTER TABLE op_oversight CHANGE `OverNameMiddle` `over_name_middle` varchar(100);
ALTER TABLE op_oversight CHANGE `OverNameLast` `over_name_last` varchar(255);
ALTER TABLE op_oversight CHANGE `OverNameSuffix` `over_name_suffix` varchar(20);
ALTER TABLE op_oversight CHANGE `OverTitle` `over_title` varchar(255);
ALTER TABLE op_oversight CHANGE `OverIDnumber` `over_id_number` varchar(50);
ALTER TABLE op_oversight CHANGE `OverWebsite` `over_website` varchar(255);
ALTER TABLE op_oversight CHANGE `OverFacebook` `over_facebook` varchar(255);
ALTER TABLE op_oversight CHANGE `OverTwitter` `over_twitter` varchar(255);
ALTER TABLE op_oversight CHANGE `OverYouTube` `over_youtube` varchar(255);
ALTER TABLE op_oversight CHANGE `OverHomepageComplaintLink` `over_homepage_complaint_link` varchar(1);
ALTER TABLE op_oversight CHANGE `OverWebComplaintInfo` `over_web_complaint_info` varchar(255);
ALTER TABLE op_oversight CHANGE `OverComplaintPDF` `over_complaint_pdf` varchar(255);
ALTER TABLE op_oversight CHANGE `OverComplaintWebForm` `over_complaint_web_form` varchar(255);
ALTER TABLE op_oversight CHANGE `OverEmail` `over_email` varchar(255);
ALTER TABLE op_oversight CHANGE `OverPhoneWork` `over_phone_work` varchar(20);
ALTER TABLE op_oversight CHANGE `OverAddress` `over_address` varchar(255);
ALTER TABLE op_oversight CHANGE `OverAddress2` `over_address2` varchar(255);
ALTER TABLE op_oversight CHANGE `OverAddressCity` `over_address_city` varchar(255);
ALTER TABLE op_oversight CHANGE `OverAddressState` `over_address_state` varchar(2);
ALTER TABLE op_oversight CHANGE `OverAddressZip` `over_address_zip` varchar(10);
ALTER TABLE op_oversight CHANGE `OverSubmitDeadline` `over_submit_deadline` int(11);
ALTER TABLE op_oversight CHANGE `OverOfficialFormNotReq` `over_official_form_not_req` int(1);
ALTER TABLE op_oversight CHANGE `OverOfficialAnon` `over_official_anon` int(1);
ALTER TABLE op_oversight CHANGE `OverWaySubOnline` `over_way_sub_online` int(1);
ALTER TABLE op_oversight CHANGE `OverWaySubEmail` `over_way_sub_email` int(1);
ALTER TABLE op_oversight CHANGE `OverWaySubVerbalPhone` `over_way_sub_verbal_phone` int(1);
ALTER TABLE op_oversight CHANGE `OverWaySubPaperMail` `over_way_sub_paper_mail` int(1);
ALTER TABLE op_oversight CHANGE `OverWaySubPaperInPerson` `over_way_sub_paper_in_person` int(1);
ALTER TABLE op_oversight CHANGE `OverWaySubNotary` `over_way_sub_notary` int(1);
ALTER TABLE op_oversight CHANGE `OverKeepEmailPrivate` `over_keep_email_private` int(1);

ALTER TABLE op_oversight_models CHANGE `OverModID` `over_mod_id` int(11);
ALTER TABLE op_oversight_models CHANGE `OverModOversightID` `over_mod_oversight_id` int(11);
ALTER TABLE op_oversight_models CHANGE `OverModCivModel` `over_mod_civ_model` int(11);

ALTER TABLE op_partner_capac CHANGE `PrtCapID` `prt_cap_id` int(11);
ALTER TABLE op_partner_capac CHANGE `PrtCapPartID` `prt_cap_part_id` int(11);
ALTER TABLE op_partner_capac CHANGE `PrtCapCapacity` `prt_cap_capacity` int(11);

ALTER TABLE op_partner_case_types CHANGE `PrtCasID` `prt_cas_id` int(11);
ALTER TABLE op_partner_case_types CHANGE `PrtCasPartnerID` `prt_cas_partner_id` int(11);

ALTER TABLE op_partner_filters CHANGE `PrtFltID` `prt_flt_id` int(11);
ALTER TABLE op_partner_filters CHANGE `PrtFltCaseID` `prt_flt_case_id` int(11);
ALTER TABLE op_partner_filters CHANGE `PrtFltFilter` `prt_flt_filter` int(11);

ALTER TABLE op_partners CHANGE `PartID` `part_id` int(11);
ALTER TABLE op_partners CHANGE `PartType` `part_type` int(11);
ALTER TABLE op_partners CHANGE `PartStatus` `part_status` tinyint(1);
ALTER TABLE op_partners CHANGE `PartUserID` `part_user_id` bigint(20);
ALTER TABLE op_partners CHANGE `PartPersonID` `part_person_id` int(11);
ALTER TABLE op_partners CHANGE `PartBio` `part_bio` text;
ALTER TABLE op_partners CHANGE `PartHelpReqs` `part_help_reqs` text;
ALTER TABLE op_partners CHANGE `PartGeoDesc` `part_geo_desc` varchar(255);
ALTER TABLE op_partners CHANGE `PartSlug` `part_slug` varchar(255);
ALTER TABLE op_partners CHANGE `PartTitle` `part_title` varchar(255);
ALTER TABLE op_partners CHANGE `PartCompanyName` `part_company_name` varchar(255);
ALTER TABLE op_partners CHANGE `PartCompanyWebsite` `part_company_website` varchar(255);
ALTER TABLE op_partners CHANGE `PartBioUrl` `part_bio_url` varchar(255);
ALTER TABLE op_partners CHANGE `PartPhotoUrl` `part_photo_url` varchar(255);
ALTER TABLE op_partners CHANGE `PartAlerts` `part_alerts` int(11);
ALTER TABLE op_partners CHANGE `PartSubmissionProgress` `part_submission_progress` int(11);
ALTER TABLE op_partners CHANGE `PartVersionAB` `part_version_ab` varchar(255);
ALTER TABLE op_partners CHANGE `PartUniqueStr` `part_unique_str` varchar(255);
ALTER TABLE op_partners CHANGE `PartIPaddy` `part_ip_addy` varchar(255);
ALTER TABLE op_partners CHANGE `PartIsMobile` `part_is_mobile` tinyint(1);

ALTER TABLE op_partner_states CHANGE `PrtStaID` `prt_sta_id` int(11);
ALTER TABLE op_partner_states CHANGE `PrtStaPartID` `prt_sta_part_id` int(11);
ALTER TABLE op_partner_states CHANGE `PrtStaState` `prt_sta_state` varchar(2);

ALTER TABLE op_person_contact CHANGE `PrsnID` `prsn_id` int(11);
ALTER TABLE op_person_contact CHANGE `PrsnUserID` `prsn_user_id` bigint(20);
ALTER TABLE op_person_contact CHANGE `PrsnNamePrefix` `prsn_name_prefix` varchar(20);
ALTER TABLE op_person_contact CHANGE `PrsnNameFirst` `prsn_name_first` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnNickname` `prsn_nickname` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnNameMiddle` `prsn_name_middle` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnNameLast` `prsn_name_last` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnNameSuffix` `prsn_name_suffix` varchar(20);
ALTER TABLE op_person_contact CHANGE `PrsnEmail` `prsn_email` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnPhoneHome` `prsn_phone_home` varchar(20);
ALTER TABLE op_person_contact CHANGE `PrsnPhoneWork` `prsn_phone_work` varchar(20);
ALTER TABLE op_person_contact CHANGE `PrsnPhoneMobile` `prsn_phone_mobile` varchar(20);
ALTER TABLE op_person_contact CHANGE `PrsnAddress` `prsn_address` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnAddress2` `prsn_address2` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnAddressCity` `prsn_address_city` varchar(255);
ALTER TABLE op_person_contact CHANGE `PrsnAddressState` `prsn_address_state` varchar(2);
ALTER TABLE op_person_contact CHANGE `PrsnAddressZip` `prsn_address_zip` varchar(10);
ALTER TABLE op_person_contact CHANGE `PrsnBirthday` `prsn_birthday` date;
ALTER TABLE op_person_contact CHANGE `PrsnFacebook` `prsn_facebook` varchar(255);

ALTER TABLE op_physical_desc CHANGE `PhysID` `phys_id` int(11);
ALTER TABLE op_physical_desc CHANGE `PhysGender` `phys_gender` varchar(1);
ALTER TABLE op_physical_desc CHANGE `PhysGenderOther` `phys_gender_other` varchar(255);
ALTER TABLE op_physical_desc CHANGE `PhysAge` `phys_age` int(11);
ALTER TABLE op_physical_desc CHANGE `PhysHeight` `phys_height` int(11);
ALTER TABLE op_physical_desc CHANGE `PhysBodyType` `phys_body_type` int(11);
ALTER TABLE op_physical_desc CHANGE `PhysHairDescription` `phys_hair_description` varchar(255);
ALTER TABLE op_physical_desc CHANGE `PhysHairFacialDesc` `phys_hair_facial_desc` varchar(255);
ALTER TABLE op_physical_desc CHANGE `PhysEyes` `phys_eyes` varchar(255);
ALTER TABLE op_physical_desc CHANGE `PhysDistinguishingMarksDesc` `phys_distinguishing_marks_desc` varchar(255);
ALTER TABLE op_physical_desc CHANGE `PhysVoiceDesc` `phys_voice_desc` varchar(255);
ALTER TABLE op_physical_desc CHANGE `PhysGeneralDesc` `phys_general_desc` varchar(255);
ALTER TABLE op_physical_desc CHANGE `PhysDisabilitiesDesc` `phys_disabilities_desc` varchar(255);

ALTER TABLE op_physical_desc_race CHANGE `PhysRaceID` `phys_race_id` int(11);
ALTER TABLE op_physical_desc_race CHANGE `PhysRacePhysDescID` `phys_race_phys_desc_id` int(11);
ALTER TABLE op_physical_desc_race CHANGE `PhysRaceRace` `phys_race_race` int(11);

ALTER TABLE op_privilege_profiles CHANGE `PrivID` `priv_id` int(11);
ALTER TABLE op_privilege_profiles CHANGE `PrivUserID` `priv_user_id` bigint(20);
ALTER TABLE op_privilege_profiles CHANGE `PrivComplaintID` `priv_complaint_id` int(11);
ALTER TABLE op_privilege_profiles CHANGE `PrivDeptID` `priv_dept_id` int(11);
ALTER TABLE op_privilege_profiles CHANGE `PrivAccessLevel` `priv_access_level` varchar(255);

ALTER TABLE op_scenes CHANGE `ScnID` `scn_id` int(11);
ALTER TABLE op_scenes CHANGE `ScnIsVehicle` `scn_is_vehicle` varchar(1);
ALTER TABLE op_scenes CHANGE `ScnIsVehicleAccident` `scn_is_vehicle_accident` varchar(1);
ALTER TABLE op_scenes CHANGE `ScnType` `scn_type` int(11);
ALTER TABLE op_scenes CHANGE `ScnDescription` `scn_description` text;
ALTER TABLE op_scenes CHANGE `ScnForcibleEntry` `scn_forcible_entry` varchar(1);
ALTER TABLE op_scenes CHANGE `ScnCCTV` `scn_cctv` varchar(1);
ALTER TABLE op_scenes CHANGE `ScnCCTVDesc` `scn_cctv_desc` text;

ALTER TABLE op_search_contra CHANGE `SrchConID` `srch_con_id` int(11);
ALTER TABLE op_search_contra CHANGE `SrchConSearchID` `srch_con_search_id` int(11);
ALTER TABLE op_search_contra CHANGE `SrchConType` `srch_con_type` int(11);

ALTER TABLE op_searches CHANGE `SrchID` `srch_id` int(11);
ALTER TABLE op_searches CHANGE `SrchEventSequenceID` `srch_event_sequence_id` int(11);
ALTER TABLE op_searches CHANGE `SrchStatedReason` `srch_stated_reason` varchar(1);
ALTER TABLE op_searches CHANGE `SrchStatedReasonDesc` `srch_stated_reason_desc` text;
ALTER TABLE op_searches CHANGE `SrchOfficerRequest` `srch_officer_request` varchar(1);
ALTER TABLE op_searches CHANGE `SrchOfficerRequestDesc` `srch_officer_request_desc` text;
ALTER TABLE op_searches CHANGE `SrchSubjectConsent` `srch_subject_consent` varchar(1);
ALTER TABLE op_searches CHANGE `SrchSubjectSay` `srch_subject_say` text;
ALTER TABLE op_searches CHANGE `SrchOfficerThreats` `srch_officer_threats` varchar(1);
ALTER TABLE op_searches CHANGE `SrchOfficerThreatsDesc` `srch_officer_threats_desc` text;
ALTER TABLE op_searches CHANGE `SrchStrip` `srch_strip` varchar(1);
ALTER TABLE op_searches CHANGE `SrchStripSearchDesc` `srch_strip_search_desc` text;
ALTER TABLE op_searches CHANGE `SrchK9sniff` `srch_k9_sniff` varchar(1);
ALTER TABLE op_searches CHANGE `SrchContrabandDiscovered` `srch_contraband_discovered` varchar(1);
ALTER TABLE op_searches CHANGE `SrchOfficerWarrant` `srch_officer_warrant` varchar(1);
ALTER TABLE op_searches CHANGE `SrchOfficerWarrantSay` `srch_officer_warrant_say` text;
ALTER TABLE op_searches CHANGE `SrchSeized` `srch_seized` varchar(1);
ALTER TABLE op_searches CHANGE `SrchSeizedDesc` `srch_seized_desc` text;
ALTER TABLE op_searches CHANGE `SrchDamage` `srch_damage` varchar(1);
ALTER TABLE op_searches CHANGE `SrchDamageDesc` `srch_damage_desc` text;
ALTER TABLE op_searches CHANGE `SrchAllegWrongfulSearch` `srch_alleg_wrongful_search` varchar(1);
ALTER TABLE op_searches CHANGE `SrchAllegWrongfulProperty` `srch_alleg_wrongful_property` varchar(1);
ALTER TABLE op_searches CHANGE `SrchAllegPropertyDamage` `srch_alleg_property_damage` varchar(1);

ALTER TABLE op_search_seize CHANGE `SrchSeizID` `srch_seiz_id` int(11);
ALTER TABLE op_search_seize CHANGE `SrchSeizSearchID` `srch_seiz_search_id` int(11);
ALTER TABLE op_search_seize CHANGE `SrchSeizType` `srch_seiz_type` int(11);

ALTER TABLE op_stop_reasons CHANGE `StopReasID` `stop_reas_id` int(11);
ALTER TABLE op_stop_reasons CHANGE `StopReasStopID` `stop_reas_stop_id` int(11);
ALTER TABLE op_stop_reasons CHANGE `StopReasReason` `stop_reas_reason` int(11);

ALTER TABLE op_stops CHANGE `StopID` `stop_id` int(11);
ALTER TABLE op_stops CHANGE `StopEventSequenceID` `stop_event_sequence_id` int(11);
ALTER TABLE op_stops CHANGE `StopStatedReasonDesc` `stop_stated_reason_desc` text;
ALTER TABLE op_stops CHANGE `StopSubjectAskedToLeave` `stop_subject_asked_to_leave` varchar(1);
ALTER TABLE op_stops CHANGE `StopSubjectStatementsDesc` `stop_subject_statements_desc` text;
ALTER TABLE op_stops CHANGE `StopEnterPrivateProperty` `stop_enter_private_property` varchar(1);
ALTER TABLE op_stops CHANGE `StopEnterPrivatePropertyDesc` `stop_enter_private_property_desc` varchar(255);
ALTER TABLE op_stops CHANGE `StopPermissionEnter` `stop_permission_enter` varchar(1);
ALTER TABLE op_stops CHANGE `StopPermissionEnterGranted` `stop_permission_enter_granted` varchar(1);
ALTER TABLE op_stops CHANGE `StopRequestID` `stop_request_id` varchar(1);
ALTER TABLE op_stops CHANGE `StopRefuseID` `stop_refuse_id` varchar(1);
ALTER TABLE op_stops CHANGE `StopRequestOfficerID` `stop_request_officer_id` varchar(1);
ALTER TABLE op_stops CHANGE `StopCitationNumber` `stop_citation_number` varchar(25);
ALTER TABLE op_stops CHANGE `StopOfficerRefuseID` `stop_officer_refuse_id` varchar(1);
ALTER TABLE op_stops CHANGE `StopSubjectFrisk` `stop_subject_frisk` varchar(1);
ALTER TABLE op_stops CHANGE `StopSubjectHandcuffed` `stop_subject_handcuffed` varchar(1);
ALTER TABLE op_stops CHANGE `StopStopSubjectHandcuffInjYN` `stop_subject_handcuff_inj_yn` varchar(1);
ALTER TABLE op_stops CHANGE `StopSubjectHandcuffInjury` `stop_subject_handcuff_injury` int(11);
ALTER TABLE op_stops CHANGE `StopChargesOther` `stop_charges_other` text;
ALTER TABLE op_stops CHANGE `StopTimeStart` `stop_time_start` datetime;
ALTER TABLE op_stops CHANGE `StopTimeEnd` `stop_time_end` datetime;
ALTER TABLE op_stops CHANGE `StopDuration` `stop_duration` int(11);
ALTER TABLE op_stops CHANGE `StopAllegWrongfulStop` `stop_alleg_wrongful_stop` varchar(1);
ALTER TABLE op_stops CHANGE `StopAllegWrongfulEntry` `stop_alleg_wrongful_entry` varchar(1);
ALTER TABLE op_stops CHANGE `StopAllegRetaliatoryCharges` `stop_alleg_retaliatory_charges` varchar(1);
ALTER TABLE op_stops CHANGE `StopBreathAlcohol` `stop_breath_alcohol` varchar(1);
ALTER TABLE op_stops CHANGE `StopBreathAlcoholFailed` `stop_breath_alcohol_failed` varchar(1);
ALTER TABLE op_stops CHANGE `StopBreathCannabis` `stop_breath_cannabis` varchar(1);
ALTER TABLE op_stops CHANGE `StopBreathCannabisFailed` `stop_breath_cannabis_failed` varchar(1);
ALTER TABLE op_stops CHANGE `StopSalivaTest` `stop_saliva_test` varchar(255);
ALTER TABLE op_stops CHANGE `StopSobrietyOther` `stop_sobriety_other` varchar(1);
ALTER TABLE op_stops CHANGE `StopSobrietyOtherDescribe` `stop_sobriety_other_describe` varchar(255);

ALTER TABLE op_surveys CHANGE `SurvID` `surv_id` int(11);
ALTER TABLE op_surveys CHANGE `SurvComplaintID` `surv_complaint_id` int(11);
ALTER TABLE op_surveys CHANGE `SurvAuthUserID` `surv_auth_user_id` bigint(20);

ALTER TABLE op_tester_beta CHANGE `BetaID` `beta_id` int(11);
ALTER TABLE op_tester_beta CHANGE `BetaEmail` `beta_email` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaName` `beta_name` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaLastName` `beta_last_name` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaYear` `beta_year` int(4);
ALTER TABLE op_tester_beta CHANGE `BetaNarrative` `beta_narrative` text;
ALTER TABLE op_tester_beta CHANGE `BetaHowHear` `beta_how_hear` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaInvited` `beta_invited` date;
ALTER TABLE op_tester_beta CHANGE `BetaVersionAB` `beta_version_ab` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaSubmissionProgress` `beta_submission_progress` int(11);
ALTER TABLE op_tester_beta CHANGE `BetaIPaddy` `beta_ip_addy` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaTreeVersion` `beta_tree_version` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaUniqueStr` `beta_unique_str` varchar(255);
ALTER TABLE op_tester_beta CHANGE `BetaUserID` `beta_user_id` bigint(20);
ALTER TABLE op_tester_beta CHANGE `BetaIsMobile` `beta_is_mobile` varchar(255);

ALTER TABLE op_vehicles CHANGE `VehicID` `vehic_id` int(11);
ALTER TABLE op_vehicles CHANGE `VehicComplaintID` `vehic_complaint_id` int(11);
ALTER TABLE op_vehicles CHANGE `VehicIsCivilian` `vehic_is_civilian` tinyint(1);
ALTER TABLE op_vehicles CHANGE `VehicTransportation` `vehic_transportation` int(11);
ALTER TABLE op_vehicles CHANGE `VehicUnmarked` `vehic_unmarked` varchar(1);
ALTER TABLE op_vehicles CHANGE `VehicVehicleMake` `vehic_vehicle_make` varchar(255);
ALTER TABLE op_vehicles CHANGE `VehicVehicleModel` `vehic_vehicle_model` varchar(255);
ALTER TABLE op_vehicles CHANGE `VehicVehicleDesc` `vehic_vehicle_desc` varchar(255);
ALTER TABLE op_vehicles CHANGE `VehicVehicleLicence` `vehic_vehicle_licence` varchar(255);
ALTER TABLE op_vehicles CHANGE `VehicVehicleNumber` `vehic_vehicle_number` varchar(20);

ALTER TABLE op_visitors CHANGE `VisID` `vis_id` int(11);
ALTER TABLE op_visitors CHANGE `VisVersionAB` `vis_version_ab` varchar(255);
ALTER TABLE op_visitors CHANGE `VisSubmissionProgress` `vis_submission_progress` int(11);
ALTER TABLE op_visitors CHANGE `VisIPaddy` `vis_ip_addy` varchar(255);
ALTER TABLE op_visitors CHANGE `VisTreeVersion` `vis_tree_version` varchar(255);
ALTER TABLE op_visitors CHANGE `VisUniqueStr` `vis_unique_str` varchar(255);
ALTER TABLE op_visitors CHANGE `VisUserID` `vis_user_id` bigint(20);
ALTER TABLE op_visitors CHANGE `VisIsMobile` `vis_is_mobile` varchar(255);

ALTER TABLE op_z_complaint_reviews CHANGE `ComRevID` `com_rev_id` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevComplaint` `com_rev_complaint` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevUser` `com_rev_user` bigint(20);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevDate` `com_rev_date` datetime;
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevType` `com_rev_type` varchar(10);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevStatus` `com_rev_status` varchar(50);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevNotAnon` `com_rev_not_anon` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevOneIncident` `com_rev_one_incident` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevCivilianContact` `com_rev_civilian_contact` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevOneOfficer` `com_rev_one_officer` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevOneAllegation` `com_rev_one_allegation` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevEvidenceUpload` `com_rev_evidence_upload` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevEnglishSkill` `com_rev_english_skill` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevReadability` `com_rev_readability` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevConsistency` `com_rev_consistency` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevRealistic` `com_rev_realistic` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevOutrage` `com_rev_outrage` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevMakeFeatured` `com_rev_make_featured` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevExplicitLang` `com_rev_explicit_lang` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevGraphicContent` `com_rev_graphic_content` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevComplaintType` `com_rev_complaint_type` int(11);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevNextAction` `com_rev_next_action` varchar(255);
ALTER TABLE op_z_complaint_reviews CHANGE `ComRevNote` `com_rev_note` longtext;

ALTER TABLE op_z_edit_departments CHANGE `ZedDeptID` `zed_dept_id` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptUserID` `zed_dept_user_id` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDuration` `zed_dept_duration` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptID` `zed_dept_dept_id` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptName` `zed_dept_dept_name` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptSlug` `zed_dept_dept_slug` varchar(100);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptType` `zed_dept_dept_type` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptStatus` `zed_dept_dept_status` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptVerified` `zed_dept_dept_verified` datetime;
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptEmail` `zed_dept_dept_email` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptPhoneWork` `zed_dept_dept_phone_work` varchar(20);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddress` `zed_dept_dept_address` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddress2` `zed_dept_dept_address2` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddressCity` `zed_dept_dept_address_city` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddressState` `zed_dept_dept_address_state` varchar(2);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddressZip` `zed_dept_dept_address_zip` varchar(10);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddressCounty` `zed_dept_dept_address_county` varchar(100);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddressLat` `zed_dept_dept_address_lat` double;
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptAddressLng` `zed_dept_dept_address_lng` double;
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptScoreOpenness` `zed_dept_dept_score_openness` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptTotOfficers` `zed_dept_dept_tot_officers` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptJurisdictionPopulation` `zed_dept_dept_jurisdiction_population` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptJurisdictionGPS` `zed_dept_dept_jurisdiction_gps` longtext;
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptVersionAB` `zed_dept_dept_version_ab` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptSubmissionProgress` `zed_dept_dept_submission_progress` int(11);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptIPaddy` `zed_dept_dept_ip_addy` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptTreeVersion` `zed_dept_dept_tree_version` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptUniqueStr` `zed_dept_dept_unique_str` varchar(255);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptUserID` `zed_dept_dept_user_id` bigint(20);
ALTER TABLE op_z_edit_departments CHANGE `ZedDeptDeptIsMobile` `zed_dept_dept_is_mobile` varchar(255);

ALTER TABLE op_z_edit_oversight CHANGE `ZedOverID` `zed_over_id` int(11);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverZedDeptID` `zed_over_zed_dept_id` int(11);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOnlineResearch` `zed_over_online_research` tinyint(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverMadeDeptCall` `zed_over_made_dept_call` tinyint(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverMadeIACall` `zed_over_made_ia_call` tinyint(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverNotes` `zed_over_notes` longtext;
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverID` `zed_over_over_id` int(11);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverType` `zed_over_over_type` int(11);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverCivModel` `zed_over_over_civ_model` int(11);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverUserID` `zed_over_over_user_id` bigint(20);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverDeptID` `zed_over_over_dept_id` int(11);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverAgncName` `zed_over_over_agnc_name` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverVerified` `zed_over_over_verified` datetime;
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverNamePrefix` `zed_over_over_name_prefix` varchar(20);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverNameFirst` `zed_over_over_name_first` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverNickname` `zed_over_over_nickname` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverNameMiddle` `zed_over_over_name_middle` varchar(100);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverNameLast` `zed_over_over_name_last` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverNameSuffix` `zed_over_over_name_suffix` varchar(20);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverTitle` `zed_over_over_title` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverIDnumber` `zed_over_over_id_number` varchar(50);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWebsite` `zed_over_over_website` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverFacebook` `zed_over_over_facebook` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverTwitter` `zed_over_over_twitter` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverYouTube` `zed_over_over_youtube` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverHomepageComplaintLink` `zed_over_over_homepage_complaint_link` varchar(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWebComplaintInfo` `zed_over_over_web_complaint_info` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverComplaintPDF` `zed_over_over_complaint_pdf` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverComplaintWebForm` `zed_over_over_complaint_web_form` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverEmail` `zed_over_over_email` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverPhoneWork` `zed_over_over_phone_work` varchar(20);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverAddress` `zed_over_over_address` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverAddress2` `zed_over_over_address2` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverAddressCity` `zed_over_over_address_city` varchar(255);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverAddressState` `zed_over_over_address_state` varchar(2);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverAddressZip` `zed_over_over_address_zip` varchar(10);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverSubmitDeadline` `zed_over_over_submit_deadline` int(11);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverOfficialFormNotReq` `zed_over_over_official_form_not_req` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverOfficialAnon` `zed_over_over_official_anon` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWaySubOnline` `zed_over_over_way_sub_online` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWaySubEmail` `zed_over_over_way_sub_email` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWaySubVerbalPhone` `zed_over_over_way_sub_verbal_phone` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWaySubPaperMail` `zed_over_over_way_sub_paper_mail` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWaySubPaperInPerson` `zed_over_over_way_sub_paper_in_person` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverWaySubNotary` `zed_over_over_way_sub_notary` int(1);
ALTER TABLE op_z_edit_oversight CHANGE `ZedOverOverKeepEmailPrivate` `zed_over_over_keep_email_private` int(1);

ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatID` `volun_stat_id` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatDate` `volun_stat_date` datetime;
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatSignups` `volun_stat_signups` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatLogins` `volun_stat_logins` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatUsersUnique` `volun_stat_users_unique` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatDeptsUnique` `volun_stat_depts_unique` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatOnlineResearch` `volun_stat_online_research` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatCallsDept` `volun_stat_calls_dept` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatCallsIA` `volun_stat_calls_ia` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatCallsTot` `volun_stat_calls_tot` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatTotalEdits` `volun_stat_total_edits` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatOnlineResearchV` `volun_stat_online_research_v` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatCallsDeptV` `volun_stat_calls_dept_v` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatCallsIAV` `volun_stat_calls_ia_v` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatCallsTotV` `volun_stat_calls_tot_v` int(11);
ALTER TABLE op_z_volun_stat_days CHANGE `VolunStatTotalEditsV` `volun_stat_total_edits_v` int(11);

ALTER TABLE op_z_volun_tmp CHANGE `TmpID` `tmp_id` int(11);
ALTER TABLE op_z_volun_tmp CHANGE `TmpUser` `tmp_user` bigint(20);
ALTER TABLE op_z_volun_tmp CHANGE `TmpType` `tmp_type` varchar(255);
ALTER TABLE op_z_volun_tmp CHANGE `TmpVal` `tmp_val` int(11);
ALTER TABLE op_z_volun_tmp CHANGE `TmpDate` `tmp_date` datetime;

ALTER TABLE op_z_volun_user_info CHANGE `UserInfoID` `user_info_id` int(11);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoUserID` `user_info_user_id` bigint(20);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoPersonContactID` `user_info_person_contact_id` int(11);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoStars` `user_info_stars` int(11);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoStars1` `user_info_stars1` int(11);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoStars2` `user_info_stars2` int(11);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoStars3` `user_info_stars3` int(11);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoDepts` `user_info_depts` int(11);
ALTER TABLE op_z_volun_user_info CHANGE `UserInfoAvgTimeDept` `user_info_avg_time_dept` int(11);



ALTER TABLE op_admin_actions MODIFY COLUMN `adm_act_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_administrators MODIFY COLUMN `adm_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_allegations MODIFY COLUMN `alle_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_alleg_silver MODIFY COLUMN `alle_sil_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_arrests MODIFY COLUMN `arst_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_body_parts MODIFY COLUMN `body_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_charges MODIFY COLUMN `chrg_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_civ_compliment MODIFY COLUMN `civ_comp_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_civilians MODIFY COLUMN `civ_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_civ_weapons MODIFY COLUMN `civ_weap_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_complaint_notes MODIFY COLUMN `note_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_complaints MODIFY COLUMN `com_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_compliments MODIFY COLUMN `compli_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_departments MODIFY COLUMN `dept_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_event_sequence MODIFY COLUMN `eve_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_evidence MODIFY COLUMN `evid_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_evidence_time MODIFY COLUMN `evi_tim_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_force MODIFY COLUMN `for_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_force_body_parts MODIFY COLUMN `frc_bdy_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_force_sub_type MODIFY COLUMN `force_sub_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_incidents MODIFY COLUMN `inc_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_injuries MODIFY COLUMN `inj_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_injury_body_parts MODIFY COLUMN `inj_bdy_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_injury_care MODIFY COLUMN `inj_care_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_civilian_allegations MODIFY COLUMN `lnk_civ_alle_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_civilian_events MODIFY COLUMN `lnk_civ_eve_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_civilian_orders MODIFY COLUMN `lnk_civ_ord_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_civilian_vehicles MODIFY COLUMN `lnk_civ_vehic_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_complaint_dept MODIFY COLUMN `lnk_com_dept_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_complaint_oversight MODIFY COLUMN `lnk_com_over_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_compliment_dept MODIFY COLUMN `lnk_compli_dept_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_compliment_oversight MODIFY COLUMN `lnk_compli_over_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_officer_allegations MODIFY COLUMN `lnk_off_alle_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_officer_dept MODIFY COLUMN `lnk_off_dept_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_officer_events MODIFY COLUMN `lnk_off_eve_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_officer_orders MODIFY COLUMN `lnk_off_ord_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_links_officer_vehicles MODIFY COLUMN `lnk_off_vehic_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_off_compliments MODIFY COLUMN `off_comp_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_officers MODIFY COLUMN `off_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_officers_verified MODIFY COLUMN `off_ver_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_orders MODIFY COLUMN `ord_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_oversight MODIFY COLUMN `over_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_oversight_models MODIFY COLUMN `over_mod_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_partner_capac MODIFY COLUMN `prt_cap_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_partner_case_types MODIFY COLUMN `prt_cas_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_partner_filters MODIFY COLUMN `prt_flt_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_partners MODIFY COLUMN `part_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_partner_states MODIFY COLUMN `prt_sta_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_person_contact MODIFY COLUMN `prsn_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_physical_desc MODIFY COLUMN `phys_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_physical_desc_race MODIFY COLUMN `phys_race_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_privilege_profiles MODIFY COLUMN `priv_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_scenes MODIFY COLUMN `scn_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_search_contra MODIFY COLUMN `srch_con_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_searches MODIFY COLUMN `srch_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_search_seize MODIFY COLUMN `srch_seiz_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_stop_reasons MODIFY COLUMN `stop_reas_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_stops MODIFY COLUMN `stop_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_surveys MODIFY COLUMN `surv_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_tester_beta MODIFY COLUMN `beta_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_vehicles MODIFY COLUMN `vehic_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_visitors MODIFY COLUMN `vis_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_z_complaint_reviews MODIFY COLUMN `com_rev_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_z_edit_departments MODIFY COLUMN `zed_dept_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_z_edit_oversight MODIFY COLUMN `zed_over_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_z_volun_stat_days MODIFY COLUMN `volun_stat_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_z_volun_tmp MODIFY COLUMN `tmp_id` int(10) AUTO_INCREMENT;
ALTER TABLE op_z_volun_user_info MODIFY COLUMN `user_info_id` int(10) AUTO_INCREMENT;




CREATE INDEX op_alleg_silver_alle_sil_complaint_idx ON op_alleg_silver(alle_sil_complaint_id);
CREATE INDEX op_allegations_alle_complaint_idx ON op_allegations(alle_complaint_id);
CREATE INDEX op_arrests_arst_event_sequence_idx ON op_arrests(arst_event_sequence_id);
CREATE INDEX op_body_parts_body_force_idx ON op_body_parts(body_force_id);
CREATE INDEX op_charges_chrg_civ_idx ON op_charges(chrg_civ_id);
CREATE INDEX op_charges_chrg_event_idx ON op_charges(chrg_event_id);
CREATE INDEX op_civ_weapons_civ_weap_com_idx ON op_civ_weapons(civ_weap_com_id);
CREATE INDEX op_civilians_civ_complaint_idx ON op_civilians(civ_complaint_id);
CREATE INDEX op_complaint_notes_note_complaint_idx ON op_complaint_notes(note_complaint_id);
CREATE INDEX op_complaint_notes_note_complaint_idx ON op_complaint_notes(note_complaint_id);
CREATE INDEX op_event_sequence_eve_complaint_idx ON op_event_sequence(eve_complaint_id);
CREATE INDEX op_force_for_event_sequence_idx ON op_force(for_event_sequence_id);
CREATE INDEX op_force_body_parts_frc_bdy_force_idx ON op_force_body_parts(frc_bdy_force_id);
CREATE INDEX op_force_sub_type_force_sub_force_idx ON op_force_sub_type(force_sub_force_id);
CREATE INDEX op_injuries_inj_subject_idx ON op_injuries(inj_subject_id);
CREATE INDEX op_injury_body_parts_inj_bdy_injury_idx ON op_injury_body_parts(inj_bdy_injury_id);
CREATE INDEX op_injury_care_inj_care_subject_idx ON op_injury_care(inj_care_subject_id);
CREATE INDEX op_links_civilian_allegations_lnk_civ_alle_civ_idx ON op_links_civilian_allegations(lnk_civ_alle_civ_id);
CREATE INDEX op_links_civilian_events_lnk_civ_eve_civ_idx ON op_links_civilian_events(lnk_civ_eve_civ_id);
CREATE INDEX op_links_civilian_orders_lnk_civ_ord_civ_idx ON op_links_civilian_orders(lnk_civ_ord_civ_id);
CREATE INDEX op_links_civilian_vehicles_lnk_civ_vehic_civ_idx ON op_links_civilian_vehicles(lnk_civ_vehic_civ_id);
CREATE INDEX op_links_complaint_oversight_lnk_com_over_dept_idx ON op_links_complaint_oversight(lnk_com_over_dept_id);
CREATE INDEX op_links_compliment_oversight_lnk_compli_over_compliment_idx ON op_links_compliment_oversight(lnk_compli_over_compliment_id);
CREATE INDEX op_links_compliment_oversight_lnk_compli_over_dept_idx ON op_links_compliment_oversight(lnk_compli_over_dept_id);
CREATE INDEX op_links_compliment_oversight_lnk_compli_over_over_idx ON op_links_compliment_oversight(lnk_compli_over_over_id);
CREATE INDEX op_links_officer_allegations_lnk_off_alle_off_idx ON op_links_officer_allegations(lnk_off_alle_off_id);
CREATE INDEX op_links_officer_allegations_lnk_off_alle_alle_idx ON op_links_officer_allegations(lnk_off_alle_alle_id);
CREATE INDEX op_links_officer_dept_lnk_off_dept_officer_idx ON op_links_officer_dept(lnk_off_dept_officer_id);
CREATE INDEX op_links_officer_dept_lnk_off_dept_dept_idx ON op_links_officer_dept(lnk_off_dept_dept_id);
CREATE INDEX op_links_officer_events_lnk_off_eve_off_idx ON op_links_officer_events(lnk_off_eve_off_id);
CREATE INDEX op_links_officer_events_lnk_off_eve_eve_idx ON op_links_officer_events(lnk_off_eve_eve_id);
CREATE INDEX op_links_officer_vehicles_lnk_off_vehic_off_idx ON op_links_officer_vehicles(lnk_off_vehic_off_id);
CREATE INDEX op_orders_ord_event_sequence_idx ON op_orders(ord_event_sequence_id);
CREATE INDEX op_person_contact_prsn_user_idx ON op_person_contact(prsn_user_id);
CREATE INDEX op_physical_desc_race_phys_race_phys_desc_idx ON op_physical_desc_race(phys_race_phys_desc_id);
CREATE INDEX op_search_contra_srch_con_search_idx ON op_search_contra(srch_con_search_id);
CREATE INDEX op_search_seize_srch_seiz_search_idx ON op_search_seize(srch_seiz_search_id);
CREATE INDEX op_searches_srch_event_sequence_idx ON op_searches(srch_event_sequence_id);
CREATE INDEX op_stop_reasons_stop_reas_stop_idx ON op_stop_reasons(stop_reas_stop_id);
CREATE INDEX op_stops_stop_event_sequence_idx ON op_stops(stop_event_sequence_id);
CREATE INDEX op_vehicles_vehic_complaint_idx ON op_vehicles(vehic_complaint_id);

CREATE INDEX op_z_complaint_reviews_com_rev_complaintx ON op_z_complaint_reviews(com_rev_complaint);
CREATE INDEX op_z_edit_departments_zed_dept_dept_idx ON op_z_edit_departments(zed_dept_dept_id);
CREATE INDEX op_z_edit_oversight_zed_over_zed_dept_idx ON op_z_edit_oversight(zed_over_zed_dept_id);
CREATE INDEX op_z_edit_oversight_zed_over_over_idx ON op_z_edit_oversight(zed_over_over_id);
/* CREATE INDEX op_z_edit_oversight_zed_over_over_dept_idx ON op_z_edit_oversight(zed_over_over_dept_id); */
CREATE INDEX op_z_volun_stat_days_volun_stat_datex ON op_z_volun_stat_days(volun_stat_date);
CREATE INDEX op_z_volun_user_info_user_info_user_idx ON op_z_volun_user_info(user_info_user_id);



CREATE INDEX op_civ_compliment_civ_comp_compliment_idx ON op_civ_compliment(civ_comp_compliment_id);
CREATE INDEX op_compliments_compli_statusx ON op_compliments(compli_status);
CREATE INDEX op_compliments_compli_typex ON op_compliments(compli_type);
CREATE INDEX op_compliments_compli_record_submittedx ON op_compliments(compli_record_submitted);
CREATE INDEX op_off_compliments_off_comp_off_idx ON op_off_compliments(off_comp_off_id);


CREATE INDEX op_departments_dept_slugx ON op_departments(dept_slug);
CREATE INDEX op_links_officer_orders_lnk_off_ord_off_idx ON op_links_officer_orders(lnk_off_ord_off_id);
CREATE INDEX op_oversight_models_over_mod_oversight_idx ON op_oversight_models(over_mod_oversight_id);
CREATE INDEX op_partner_capac_prt_cap_part_idx ON op_partner_capac(prt_cap_part_id);
CREATE INDEX op_partner_case_types_prt_cas_partner_idx ON op_partner_case_types(prt_cas_partner_id);
CREATE INDEX op_partner_filters_prt_flt_case_idx ON op_partner_filters(prt_flt_case_id);
CREATE INDEX op_partner_states_prt_sta_part_idx ON op_partner_states(prt_sta_part_id);







